name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'
    - uses: actions/checkout@v3
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test --enable-code-coverage
    
    - name: Swift Coverage Report # .build/debug/codecov/lcov.info
      uses: maxep/spm-lcov-action@0.3.1 

    - uses: codecov/codecov-action@v3
      with:
        files: .build/debug/codecov/lcov.info
        flags: unittests # optional
        fail_ci_if_error: true
