name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
        release: [ debug, release ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.release }}

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'
    - uses: actions/checkout@v3
    
    - name: Build debug
      run: swift build -c ${{ matrix.release }}

    - name: Run tests
      run: swift test -c ${{ matrix.release }} -Xswiftc -enable-testing -Xswiftc -DRELEASE_TEST --enable-code-coverage
    
    - name: Swift Coverage Report # .build/debug/codecov/lcov.info
      if: ${{ matrix.release == 'Debug' && matrix.os == 'ubuntu-latest' }}
      uses: maxep/spm-lcov-action@0.3.1 

    - uses: codecov/codecov-action@v3
      if: ${{ matrix.release == 'Debug' && matrix.os == 'ubuntu-latest' }}
      with:
        files: .build/debug/codecov/lcov.info
        flags: unittests # optional
        fail_ci_if_error: true
