name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        release: [ true, false ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'
    - uses: actions/checkout@v3
    
    - name: Build
      run: swift build
    
    - name: Run debug tests
      if: ${{ !matrix.release }}
      run: swift test --enable-code-coverage

    - name: Run release tests
      if: ${{ matrix.release }}
      run: swift test -c release -Xswiftc -enable-testing -Xswiftc -DRELEASE_TEST --enable-code-coverage
    
    - name: Swift Coverage Report # .build/debug/codecov/lcov.info
      if: ${{ !matrix.release && matrix.os == 'ubuntu-latest' }}
      uses: maxep/spm-lcov-action@0.3.1 

    - uses: codecov/codecov-action@v3
      if: ${{ !matrix.release && matrix.os == 'ubuntu-latest' }}
      with:
        files: .build/debug/codecov/lcov.info
        flags: unittests # optional
        fail_ci_if_error: true
